package model

// empty IP
var EMPTY_VIRTUAL_IP VirtualIp = MakeVirtualIp("")

// handler protocols
const TEST_DATA_PROTOCOL = 0
const TRANSPORT_PROTOCOL = 0
const RIP_PROTOCOL = 200

// IP header
const IP_VERSION = 4
const IP_DEFAUTL_HEADER_LEN = 20
const IP_DEFAULT_TOS = 0
const IP_DEFAULT_TTL = 16
const IP_DEFAULT_ID = 0
const IP_DEFAULT_FLAGS = 0
const IP_DEFAULT_OFFSET = 0

// RIP
const RIP_BROADCAST_INTERVAL_MILLIS = 5000
const RIP_TRIGGERED_UPDATE_INTERVAL_MILLIS = 500
const RIP_REQUEST_COMMAND = 1
const RIP_RESPONSE_COMMAND = 2
const RIP_INFINITY = 16
const RIP_ROUTING_ENTRY_TTL_SECONDS = 12
const RIP_GC_TIMER_SECONDS = 6

// UDP
const UDP_MTU = 1400
const UDP_RECEIVE_MAX_BUFFER_SIZE = 64 * 1024
